static const int lua_to_cy[] = {
    29, // OP_MOVE
    23, // OP_LOADK
    24, // OP_LOADKX
    10, // OP_LOADBOOL
    21, // OP_LOADNIL
    9, // OP_GETUPVAL
    30, // OP_GETTABUP
    38, // OP_GETTABLE
    12, // OP_SETTABUP
    3, // OP_SETUPVAL
    35, // OP_SETTABLE
    4, // OP_NEWTABLE
    42, // OP_SELF
    26, // OP_ADD
    11, // OP_SUB
    33, // OP_MUL
    28, // OP_MOD
    46, // OP_POW
    18, // OP_DIV
    31, // OP_IDIV
    45, // OP_BAND
    32, // OP_BOR
    36, // OP_BXOR
    25, // OP_SHL
    20, // OP_SHR
    22, // OP_UNM
    39, // OP_BNOT
    43, // OP_NOT
    0, // OP_LEN
    19, // OP_CONCAT
    16, // OP_JMP
    41, // OP_EQ
    13, // OP_LT
    37, // OP_LE
    44, // OP_TEST
    2, // OP_TESTSET
    27, // OP_CALL
    5, // OP_TAILCALL
    34, // OP_RETURN
    6, // OP_FORLOOP
    8, // OP_FORPREP
    14, // OP_TFORCALL
    15, // OP_TFORLOOP
    17, // OP_SETLIST
    1, // OP_CLOSURE
    7, // OP_VARARG
    40, // OP_EXTRAARG
};

static const int cy_to_lua[] = {
    28, // CYOP_LEN
    44, // CYOP_CLOSURE
    35, // CYOP_TESTSET
    9, // CYOP_SETUPVAL
    11, // CYOP_NEWTABLE
    37, // CYOP_TAILCALL
    39, // CYOP_FORLOOP
    45, // CYOP_VARARG
    40, // CYOP_FORPREP
    5, // CYOP_GETUPVAL
    3, // CYOP_LOADBOOL
    14, // CYOP_SUB
    8, // CYOP_SETTABUP
    32, // CYOP_LT
    41, // CYOP_TFORCALL
    42, // CYOP_TFORLOOP
    30, // CYOP_JMP
    43, // CYOP_SETLIST
    18, // CYOP_DIV
    29, // CYOP_CONCAT
    24, // CYOP_SHR
    4, // CYOP_LOADNIL
    25, // CYOP_UNM
    1, // CYOP_LOADK
    2, // CYOP_LOADKX
    23, // CYOP_SHL
    13, // CYOP_ADD
    36, // CYOP_CALL
    16, // CYOP_MOD
    0, // CYOP_MOVE
    6, // CYOP_GETTABUP
    19, // CYOP_IDIV
    21, // CYOP_BOR
    15, // CYOP_MUL
    38, // CYOP_RETURN
    10, // CYOP_SETTABLE
    22, // CYOP_BXOR
    33, // CYOP_LE
    7, // CYOP_GETTABLE
    26, // CYOP_BNOT
    46, // CYOP_EXTRAARG
    31, // CYOP_EQ
    12, // CYOP_SELF
    27, // CYOP_NOT
    34, // CYOP_TEST
    20, // CYOP_BAND
    17, // CYOP_POW
};
